### ISSUE TITLE
NPE thrown in oscm-identity when operating with custom tenant

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-identity#65]
**Version Info**
OSCM 18.1, SSO branch 28.10.2019

**Describe the bug**
NPE thrown in oscm-identity

**How to Reproduce**
Very sorry, I didn't record the details steps. I was testing with a custom tenant, login and logout from marketplace for investigating [oscm#524](https://github.com/servicecatalog/oscm/issues/524)
I don't believe that I did something very different from the steps listed in this bug. However it seems this issue is not reproducing always. Nevertheless, the stacktrace should be helpful. Please go for that.

**Observed behavior**
Nullpointer Exception with following error trace was logged in oscm-identity container.
java.lang.NullPointerException: null
        at org.oscm.identity.oidc.request.RequestHandler.getRequestManager(RequestHandler.java:40) ~[classes!/:1.0-SNAPSHOT]
        at org.oscm.identity.controller.MainController.loginPage(MainController.java:61) ~[classes!/:1.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
        at....

**Expected behavior**
No error entries.

**Screenshots**
If applicable, screenshots to help explain your problem.

**Additional context**
Ask me - I can share you my custom tenant setup.

**Comment by adamczykba** [comment]
@GoebelL 
Could You please enclose the tenant configuration property file, that You were using to test this behaviour?

**Comment by GoebelL** [comment]
@adamczykba 
Sure. I just sent it on slack.

**Comment by adamczykba** [comment]
@GoebelL 
I wasn't able to reproduce the error but instead implemented some additional validation for tenant config, just to be safe in the future
